package edu.stratford.rbandlar8760.rssfeeds.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import edu.stratford.rbandlar8760.rssfeeds.db.MappingDetails;

/**
 * Class _Category was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Category extends CayenneDataObject {

    public static final String CATEGORY_NAME_PROPERTY = "categoryName";
    public static final String MAPPING_DETAILS_ARRAY_PROPERTY = "mappingDetailsArray";

    public static final String S_NO_PK_COLUMN = "s_no";

    public void setCategoryName(String categoryName) {
        writeProperty("categoryName", categoryName);
    }
    public String getCategoryName() {
        return (String)readProperty("categoryName");
    }

    public void addToMappingDetailsArray(MappingDetails obj) {
        addToManyTarget("mappingDetailsArray", obj, true);
    }
    public void removeFromMappingDetailsArray(MappingDetails obj) {
        removeToManyTarget("mappingDetailsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MappingDetails> getMappingDetailsArray() {
        return (List<MappingDetails>)readProperty("mappingDetailsArray");
    }


}
