package edu.stratford.rbandlar8760.rssfeeds.db.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Company was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Company extends CayenneDataObject {

    public static final String COMPANY_NAME_PROPERTY = "companyName";

    public static final String COMPANY_ID_PK_COLUMN = "company_id";

    public void setCompanyName(String companyName) {
        writeProperty("companyName", companyName);
    }
    public String getCompanyName() {
        return (String)readProperty("companyName");
    }

}
