package edu.stratford.rbandlar8760.rssfeeds.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import edu.stratford.rbandlar8760.rssfeeds.db.MappingDetails;

/**
 * Class _Company was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Company extends CayenneDataObject {

    public static final String COMPANY_NAME_PROPERTY = "companyName";
    public static final String MAPPING_DETAILS_ARRAY_PROPERTY = "mappingDetailsArray";

    public static final String COMPANY_ID_PK_COLUMN = "company_id";

    public void setCompanyName(String companyName) {
        writeProperty("companyName", companyName);
    }
    public String getCompanyName() {
        return (String)readProperty("companyName");
    }

    public void addToMappingDetailsArray(MappingDetails obj) {
        addToManyTarget("mappingDetailsArray", obj, true);
    }
    public void removeFromMappingDetailsArray(MappingDetails obj) {
        removeToManyTarget("mappingDetailsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MappingDetails> getMappingDetailsArray() {
        return (List<MappingDetails>)readProperty("mappingDetailsArray");
    }


}
