package edu.stratford.rbandlar8760.rssfeeds.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import edu.stratford.rbandlar8760.rssfeeds.db.ProductDetails;
import edu.stratford.rbandlar8760.rssfeeds.db.TagDetails;

/**
 * Class _Information was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Information extends CayenneDataObject {

    public static final String INFORMATION_PROPERTY = "information";
    public static final String PRODUCT_DETAILS_ARRAY_PROPERTY = "productDetailsArray";
    public static final String TAG_DETAILS_ARRAY_PROPERTY = "tagDetailsArray";

    public static final String INF_PK_PK_COLUMN = "inf_pk";

    public void setInformation(String information) {
        writeProperty("information", information);
    }
    public String getInformation() {
        return (String)readProperty("information");
    }

    public void addToProductDetailsArray(ProductDetails obj) {
        addToManyTarget("productDetailsArray", obj, true);
    }
    public void removeFromProductDetailsArray(ProductDetails obj) {
        removeToManyTarget("productDetailsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ProductDetails> getProductDetailsArray() {
        return (List<ProductDetails>)readProperty("productDetailsArray");
    }


    public void addToTagDetailsArray(TagDetails obj) {
        addToManyTarget("tagDetailsArray", obj, true);
    }
    public void removeFromTagDetailsArray(TagDetails obj) {
        removeToManyTarget("tagDetailsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TagDetails> getTagDetailsArray() {
        return (List<TagDetails>)readProperty("tagDetailsArray");
    }


}
