package edu.stratford.rbandlar8760.rssfeeds.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import edu.stratford.rbandlar8760.rssfeeds.db.Category;
import edu.stratford.rbandlar8760.rssfeeds.db.Company;
import edu.stratford.rbandlar8760.rssfeeds.db.ProductDetails;

/**
 * Class _MappingDetails was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MappingDetails extends CayenneDataObject {

    public static final String PRODUCT_DETAILS_ARRAY_PROPERTY = "productDetailsArray";
    public static final String TO_CATEGORY_PROPERTY = "toCategory";
    public static final String TO_CATEGORY1_PROPERTY = "toCategory1";
    public static final String TO_COMPANY_PROPERTY = "toCompany";

    public static final String MAP_ID_PK_COLUMN = "map_id";

    public void addToProductDetailsArray(ProductDetails obj) {
        addToManyTarget("productDetailsArray", obj, true);
    }
    public void removeFromProductDetailsArray(ProductDetails obj) {
        removeToManyTarget("productDetailsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ProductDetails> getProductDetailsArray() {
        return (List<ProductDetails>)readProperty("productDetailsArray");
    }


    public void setToCategory(Category toCategory) {
        setToOneTarget("toCategory", toCategory, true);
    }

    public Category getToCategory() {
        return (Category)readProperty("toCategory");
    }


    public void setToCategory1(Category toCategory1) {
        setToOneTarget("toCategory1", toCategory1, true);
    }

    public Category getToCategory1() {
        return (Category)readProperty("toCategory1");
    }


    public void setToCompany(Company toCompany) {
        setToOneTarget("toCompany", toCompany, true);
    }

    public Company getToCompany() {
        return (Company)readProperty("toCompany");
    }


}
