package edu.stratford.rbandlar8760.rssfeeds.db.auto;

import org.apache.cayenne.CayenneDataObject;

import edu.stratford.rbandlar8760.rssfeeds.db.Information;
import edu.stratford.rbandlar8760.rssfeeds.db.MappingDetails;

/**
 * Class _ProductDetails was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ProductDetails extends CayenneDataObject {

    public static final String VALUE_PROPERTY = "value";
    public static final String TO_INFORMATION_PROPERTY = "toInformation";
    public static final String TO_MAPPING_DETAILS_PROPERTY = "toMappingDetails";


    public void setValue(String value) {
        writeProperty("value", value);
    }
    public String getValue() {
        return (String)readProperty("value");
    }

    public void setToInformation(Information toInformation) {
        setToOneTarget("toInformation", toInformation, true);
    }

    public Information getToInformation() {
        return (Information)readProperty("toInformation");
    }


    public void setToMappingDetails(MappingDetails toMappingDetails) {
        setToOneTarget("toMappingDetails", toMappingDetails, true);
    }

    public MappingDetails getToMappingDetails() {
        return (MappingDetails)readProperty("toMappingDetails");
    }


}
