package edu.stratford.rbandlar8760.rssfeeds.db.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import edu.stratford.rbandlar8760.rssfeeds.db.MappingDetails;

/**
 * Class _ProductDetails was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ProductDetails extends CayenneDataObject {

    public static final String DATE_PROPERTY = "date";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String LINK_PROPERTY = "link";
    public static final String TITLE_PROPERTY = "title";
    public static final String TO_MAPPING_DETAILS_PROPERTY = "toMappingDetails";

    public static final String PRODUCT_DETAILS_ID_PK_COLUMN = "product_details_id";

    public void setDate(Date date) {
        writeProperty("date", date);
    }
    public Date getDate() {
        return (Date)readProperty("date");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setLink(String link) {
        writeProperty("link", link);
    }
    public String getLink() {
        return (String)readProperty("link");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setToMappingDetails(MappingDetails toMappingDetails) {
        setToOneTarget("toMappingDetails", toMappingDetails, true);
    }

    public MappingDetails getToMappingDetails() {
        return (MappingDetails)readProperty("toMappingDetails");
    }


}
