package edu.stratford.rbandlar8760.rssfeeds.db.auto;

import org.apache.cayenne.CayenneDataObject;

import edu.stratford.rbandlar8760.rssfeeds.db.Information;
import edu.stratford.rbandlar8760.rssfeeds.db.Website;

/**
 * Class _TagDetails was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TagDetails extends CayenneDataObject {

    public static final String TAGNAME_PROPERTY = "tagname";
    public static final String TO_INFORMATION_PROPERTY = "toInformation";
    public static final String TO_WEBSITE_PROPERTY = "toWebsite";

    public static final String TAG_ID_PK_COLUMN = "tag_id";

    public void setTagname(String tagname) {
        writeProperty("tagname", tagname);
    }
    public String getTagname() {
        return (String)readProperty("tagname");
    }

    public void setToInformation(Information toInformation) {
        setToOneTarget("toInformation", toInformation, true);
    }

    public Information getToInformation() {
        return (Information)readProperty("toInformation");
    }


    public void setToWebsite(Website toWebsite) {
        setToOneTarget("toWebsite", toWebsite, true);
    }

    public Website getToWebsite() {
        return (Website)readProperty("toWebsite");
    }


}
