package edu.stratford.rbandlar8760.rssfeeds.db.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import edu.stratford.rbandlar8760.rssfeeds.db.MappingDetails;
import edu.stratford.rbandlar8760.rssfeeds.db.TagDetails;
import edu.stratford.rbandlar8760.rssfeeds.db.WebsiteUrl;

/**
 * Class _Website was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Website extends CayenneDataObject {

    public static final String WEBSITE_NAME_PROPERTY = "websiteName";
    public static final String MAPPING_DETAILS_ARRAY_PROPERTY = "mappingDetailsArray";
    public static final String TAG_DETAILS_ARRAY_PROPERTY = "tagDetailsArray";
    public static final String WEBSITE_URL_ARRAY_PROPERTY = "websiteUrlArray";

    public static final String WEB_PK_PK_COLUMN = "web_pk";

    public void setWebsiteName(String websiteName) {
        writeProperty("websiteName", websiteName);
    }
    public String getWebsiteName() {
        return (String)readProperty("websiteName");
    }

    public void addToMappingDetailsArray(MappingDetails obj) {
        addToManyTarget("mappingDetailsArray", obj, true);
    }
    public void removeFromMappingDetailsArray(MappingDetails obj) {
        removeToManyTarget("mappingDetailsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MappingDetails> getMappingDetailsArray() {
        return (List<MappingDetails>)readProperty("mappingDetailsArray");
    }


    public void addToTagDetailsArray(TagDetails obj) {
        addToManyTarget("tagDetailsArray", obj, true);
    }
    public void removeFromTagDetailsArray(TagDetails obj) {
        removeToManyTarget("tagDetailsArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TagDetails> getTagDetailsArray() {
        return (List<TagDetails>)readProperty("tagDetailsArray");
    }


    public void addToWebsiteUrlArray(WebsiteUrl obj) {
        addToManyTarget("websiteUrlArray", obj, true);
    }
    public void removeFromWebsiteUrlArray(WebsiteUrl obj) {
        removeToManyTarget("websiteUrlArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebsiteUrl> getWebsiteUrlArray() {
        return (List<WebsiteUrl>)readProperty("websiteUrlArray");
    }


}
