package edu.stratford.rbandlar8760.rssfeeds.db.auto;

import org.apache.cayenne.CayenneDataObject;

import edu.stratford.rbandlar8760.rssfeeds.db.Website;

/**
 * Class _WebsiteUrl was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebsiteUrl extends CayenneDataObject {

    public static final String URL_PROPERTY = "url";
    public static final String TO_WEBSITE_PROPERTY = "toWebsite";

    public static final String WEBSITE_URL_PK_PK_COLUMN = "website_url_pk";

    public void setUrl(String url) {
        writeProperty("url", url);
    }
    public String getUrl() {
        return (String)readProperty("url");
    }

    public void setToWebsite(Website toWebsite) {
        setToOneTarget("toWebsite", toWebsite, true);
    }

    public Website getToWebsite() {
        return (Website)readProperty("toWebsite");
    }


}
